// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClLz025nHsZzMAu19oivUQseOJKlKcmfk',
    appId: '1:659457566191:web:fe5bd16347d9a8a0d7821a',
    messagingSenderId: '659457566191',
    projectId: 'recipe-app-7506d',
    authDomain: 'recipe-app-7506d.firebaseapp.com',
    storageBucket: 'recipe-app-7506d.appspot.com',
    measurementId: 'G-V6HRHQLV2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgVyqCh2EPCT8GRe2Xq47x_2pL4s7NuvY',
    appId: '1:659457566191:android:f2fd9112b4456998d7821a',
    messagingSenderId: '659457566191',
    projectId: 'recipe-app-7506d',
    storageBucket: 'recipe-app-7506d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlat2nWbuE_4AuYcq0G_oO70aCf2N-9eM',
    appId: '1:659457566191:ios:5a52f36cfeea256bd7821a',
    messagingSenderId: '659457566191',
    projectId: 'recipe-app-7506d',
    storageBucket: 'recipe-app-7506d.appspot.com',
    iosClientId: '659457566191-1ndocagho2gfm6o29e857uena9078925.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlat2nWbuE_4AuYcq0G_oO70aCf2N-9eM',
    appId: '1:659457566191:ios:5a52f36cfeea256bd7821a',
    messagingSenderId: '659457566191',
    projectId: 'recipe-app-7506d',
    storageBucket: 'recipe-app-7506d.appspot.com',
    iosClientId: '659457566191-1ndocagho2gfm6o29e857uena9078925.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
